import { NavBar } from '@/components/navbar'
import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import Script from 'next/script'
import "./globals.css"

// Настройка Poppins с нужными начертаниями
const poppins = Poppins({
  weight: ['400', '500', '600', '700'], // Выберите нужные варианты толщины
  subsets: ["latin"],
  variable: "--font-poppins",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <head>
        <Script 
          src="https://telegram.org/js/telegram-web-app.js?57" 
          strategy="beforeInteractive" 
        />
      </head>
        <body style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
          <main style={{ flex: '1' }}>
            {children}
          </main>
          <NavBar />
        </body>
    </html>
  );
}